### ISSUE TITLE
long meshing times with heavy duty constraints

### ISSUE THREAD

**Issue by krober10nd** [dengwirda/mesh2d#14]
Hey Darren, 

I have a meshing problem where I'd like to constrain the red lines in the blue polygon region below. There's a lot of constraints and what I find is that passing some configurations of constraints lead to non-convergence. 

Are there any geometry pre-processing/clean up that I can do with the constraints that I can do to perhaps avoid this? 

![question1](https://user-images.githubusercontent.com/18619644/115125688-44a24100-9fa0-11eb-96e6-ec1c4c21182d.png)

![question2](https://user-images.githubusercontent.com/18619644/115125691-45d36e00-9fa0-11eb-8094-87145ab427ad.png)

Thanks!

**Comment by krober10nd** [comment]
Here are some profiling results which maybe can give you some indication of what's going on.

<img width="1440" alt="Screen Shot 2021-04-17 at 5 18 07 PM" src="https://user-images.githubusercontent.com/18619644/115125791-e3c73880-9fa0-11eb-9017-67e59a1fa988.png">

**Comment by dengwirda** [comment]
I'm happy to take a quick look at the geometry here @krober10nd, if you can save it to file. It looks fairly skinny in places, so may require many cells...

If there's non-convergence occurring this is definitely worth getting to the bottom of. If it's more of a performance issue though switching to [`jigsaw`](https://github.com/dengwirda/jigsaw) is possibly worth pursuing (the [`jigsaw-matlab`](https://github.com/dengwirda/jigsaw-matlab) and/or [`jigsaw-python`](https://github.com/dengwirda/jigsaw-python) bindings are available for script-based work). 

I am keen to keep `mesh2d` working into the future, but it's mostly for historical reasons at this stage --- the `jigsaw`-based algorithms + workflows are the focus for any new dev.

**Comment by krober10nd** [comment]
Hey @dengwirda I ended up figuring it out myself. Some "bad" geometry. Worked just fine took a couple minutes.

**Comment by dengwirda** [comment]
Hi @krober10nd, just checking whether you're looking to use `mesh2d` in `oceanmesh2d`? I had a quick look, and there seem to be a few routines from `mesh2d` in the repo these days.

No problem to do this of course, but can you add a few references/links, etc if this is the case.

**Comment by krober10nd** [comment]
@dengwirda yep we've been using it recently combining the two approaches for some workflows (like the one I've shown above). 

We did add references in the individual files to you and folders but please let me know if that is not sufficient.

For example 

https://github.com/CHLNDDEV/OceanMesh2D/tree/Projection/utilities/GEOM_UTIL

https://github.com/CHLNDDEV/OceanMesh2D/blob/Projection/utilities/smooth2.m

https://github.com/CHLNDDEV/OceanMesh2D/blob/Projection/utilities/limgrad.m

https://github.com/CHLNDDEV/OceanMesh2D/blob/Projection/utilities/inpoly.m

etc.

Would you like further acknowledgement at the README level too? We can do that as well as I'm very grateful for your help over the years. @wpringle

**Comment by WPringle** [comment]
@dengwirda @krober10nd , How does [this](https://github.com/CHLNDDEV/OceanMesh2D/pull/216) look?

**Comment by dengwirda** [comment]
Thanks @WPringle, @krober10nd --- looks good!

Also, just for reference: the historical `mesh2d` was initially based on a spring-based method a'la `distmesh`, but these days is more of a cut-down `jigsaw` (a brand of Delaunay-refinement). It is possible to call the full `jigsaw` from within `MATLAB` (`Python`, etc). Happy to discuss if this is of interest.
