### ISSUE TITLE
Download of mesh2d

### ISSUE THREAD

**Issue by ypzpy** [dengwirda/mesh2d#15]
Hi, I'm trying to download mesh2d from the github repository. But when I ran some sample code in matlab, it's still saying that the function is not found. Could you suggest the correct way of downloading the function? Thank you!

**Comment by dengwirda** [comment]
I'm not sure @ypzpy, the typical process is to download the code, unzip it, add it to your `matlab` path and ensure you call `initmsh()` before any `mesh2d` routines.
The `readme` contains additional information, as well as the examples in `tridemo`.

**Comment by dengwirda** [comment]
I'm hoping the suggestions above resolved any issues so am closing this. Let me know if you continue to run into problems.
