### ISSUE TITLE
refine2 without introducing additional border nodes

### ISSUE THREAD

**Issue by austinherrema** [dengwirda/mesh2d#7]
I am wondering if it is possible to use the `refine2()` function to generate a mesh in which no new nodes are added on the border of the polygonal geometry. I have experimented with the various `refine2` options (RHO1, SIZ1, SIZ2, etc.) and have been unable to achieve this, though my understanding of the effect of some of the options is limited. In my case, I care more about the no-new-border-nodes requirement than the final mesh quality. Is there any way to achieve this, either directly or indirectly?

**Comment by dengwirda** [comment]
@austinherrema Yes, there are some new options `OPTS.REF1` and `OPTS.REF2` that can be set to `preserve` (rather than the default `refine`) to preserve the boundary cells as you've specified them. Of course, this can lead to some potential compromises in terms of mesh quality constraints; specifically, it's not possible to guarantee that cells in the 'neighbourhood' of unrefinable boundary segments satisfy their requested bounds... In practice though, as long as your boundary discretisation matches the interior constraints reasonably well enough, you should get a good mesh that preserves an existing boundary.

**Comment by austinherrema** [comment]
@dengwirda Thanks for the help. I updated mesh2d and tried to use the new `OPTS.REF1` and `OPTS.REF2` options (setting them both to `preserve`). Unfortunately, `refine2` still appears to introduce new nodes. See the below figure, which shows a portion of the geometry for which I am generating a mesh. The input nodes are indicated by red markers.

![image](https://user-images.githubusercontent.com/29387274/43612257-fd2d2bc0-9668-11e8-83ed-a5b3f90ebdba.png)

Are there any other options I can change to achieve the desired behavior? Oddly, tweaking `RHO2`, `SIZ1`, and `SIZ2` seems to have no effect on the final mesh.

Obviously the final mesh for this geometry will be quite odd if no new nodes are introduced, but this is acceptable for my application.

**Comment by dengwirda** [comment]
@austinherrema I've had a chance to look into this, but am having trouble reproducing the behaviour you've shown. Can you email me the geometry, etc that you're specifying, along with details on the `MATLAB` / `OCTAVE` release that you're using?

**Comment by austinherrema** [comment]
@dengwirda I sent an email; please let me know if you do not receive anything or need more info!

**Comment by dengwirda** [comment]
@austinherrema Ah -- easy I think! `MATLAB` is case-sensitive, so `opts.REF1` isn't quite the same thing as `opts.ref1`... (the lower-case version is what you're looking for here and seems to behave as expected I think).

I should perhaps change the error-checking that's done on the `opts` structure to catch these kind of cases with unrecognised fieldnames.

**Comment by austinherrema** [comment]
@dengwirda Sure enough--using lowercase `opts.ref1` and `opts.ref2` produces the desired result. Thank you! I definitely should have tried that earlier, but I'm glad it was a straightforward solution.

For what it's worth, I think I used capitalized versions of the options because that is how they are presented in the `refine2` help (`OPTS.REF1 = {'REFINE'}, 'PRESERVE'...`). Of course, I see now that that the capitalization was simply intended to set each option apart from its description.

Thanks for your great work on this tool!
