### ISSUE TITLE
Error in deltri2 (during refine2) when meshing multi-part geometry

### ISSUE THREAD

**Issue by austinherrema** [dengwirda/mesh2d#8]
I am running into a strange error when meshing a 3-part geometry. The traceback is as follows:

``` Matlab
Index in position 1 exceeds array bounds (must not exceed 269).
Error in deltri2 (line 138)
    tmid = vert(tria(:,1),:) ...
Error in refine2>cdtbal0 (line 311)
        tria,tnum] = deltri2(vert,conn, ...
Error in refine2 (line 260)
        cdtbal0(vert,conn,tria,tnum, ...
```

The index in question exists in the `tria` variable and has a value of 270 (vert only goes up to 269). Oddly, when I mesh the three parts separately, or even in sets of two parts at a time--i.e. parts 1 and 2, parts 2 and 3, etc.--then I do not encounter this error.

Do you expect that this may be indicative of some kind of input error? Any suggestions of things to try? Let me know if this is simply too difficult to diagnose without some kind of example geometry and I'll see what I can do...

**Comment by dengwirda** [comment]
@austinherrema Yes, I think it'll be hard to track down without the details. If you can send me an example problem I'm happy to look into it.

**Comment by austinherrema** [comment]
@dengwirda Thanks for your response! Unfortunately, after some experimentation, I am only able to generate this error with a very specific geometry which happens to contain some company IP which I am unable to share. If I am able to achieve the error with a shareable geometry, I will be sure to let you know.

**Comment by dengwirda** [comment]
@austinherrema No worries. If this continues to give you trouble you could consider an NDA - I'm happy to keep geometry/data/etc confidential.
